/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author kacpe
 */
public class DataUpdateWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataUpdateWindow.class.getName());

    /**
     * Creates new form DataUpdateWindow
     */
    public DataUpdateWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jKod = new javax.swing.JTextField();
        jNazwisko = new javax.swing.JTextField();
        jNumer = new javax.swing.JTextField();
        jTelefon = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jAkceptuj = new javax.swing.JButton();
        jAnuluj = new javax.swing.JButton();
        jFormattedData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jKategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jKod.setEditable(false);
        jKod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKodActionPerformed(evt);
            }
        });

        jNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNazwiskoActionPerformed(evt);
            }
        });

        jNumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumerActionPerformed(evt);
            }
        });

        jTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonActionPerformed(evt);
            }
        });

        jEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Kod");

        jLabel2.setText("Imię i Nazwisko");

        jLabel3.setText("Telefon");

        jLabel4.setText("E-mail");

        jLabel5.setText("Data Przyjęcia/Wejścia");

        jLabel7.setText("Numer Identyfikacyjny");

        jAkceptuj.setBackground(new java.awt.Color(51, 255, 0));
        jAkceptuj.setForeground(new java.awt.Color(0, 0, 0));
        jAkceptuj.setText("Akceptuj");

        jAnuluj.setBackground(new java.awt.Color(255, 0, 0));
        jAnuluj.setForeground(new java.awt.Color(0, 0, 0));
        jAnuluj.setText("Anuluj");

        jFormattedData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedDataActionPerformed(evt);
            }
        });

        jLabel8.setText("Kategoria");

        jKategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jAkceptuj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jAnuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jKategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(jFormattedData)
                        .addComponent(jEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jNumer, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jNazwisko, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jKod, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnuluj)
                    .addComponent(jAkceptuj))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKodActionPerformed

    private void jNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNazwiskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNazwiskoActionPerformed

    private void jNumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumerActionPerformed

    private void jTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefonActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jFormattedDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedDataActionPerformed

    private void jKategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataUpdateWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jAkceptuj;
    public javax.swing.JButton jAnuluj;
    public javax.swing.JTextField jEmail;
    public javax.swing.JTextField jFormattedData;
    public javax.swing.JTextField jKategoria;
    public javax.swing.JTextField jKod;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField jNazwisko;
    public javax.swing.JTextField jNumer;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTelefon;
    // End of variables declaration//GEN-END:variables


// Wewnątrz klasy Views.DataUpdateWindow:

// --- Metody pobierające dane z pól (dodaj te metody) ---
public String getKod() {
    return jKod.getText();
}

public String getNazwisko() {
    return jNazwisko.getText();
}

public String getNumerIdentyfikacyjny() {
    return jNumer.getText(); // Zakładam, że to Numer Identyfikacyjny (ID)
}

public String getTelefon() {
    return jTelefon.getText();
}

public String getEmail() {
    return jEmail.getText();
}
public String getKategoria() {
    return jKategoria.getText();
}

// Póki co Nick i Data zostawmy jako String, dla uproszczenia


// Data jest w JFormattedTextField
public Object getFormattedData() {
    return jFormattedData.getText(); // To zwróci sparsowaną datę (jeśli formatowanie działa)
    // Dla prostoty, można by to po prostu zwrócić jako String: jFormattedData.getText();
}
public void setKod(String kod) {
    jKod.setText(kod);
}

public void setNazwisko(String nazwisko) {
    jNazwisko.setText(nazwisko);
}

public void setNumerIdentyfikacyjny(String numer) {
    jNumer.setText(numer);
}

public void setTelefon(String telefon) {
    jTelefon.setText(telefon);
}

public void setEmail(String email) {
    jEmail.setText(email);
}

public void setKategoria(String kategoria) {
    // UŻYWA jKategoria1, a NIE jFormattedData
    jKategoria.setText(kategoria); 
}



/**
 * Ustawia wartość JFormattedTextField. Należy ustawiać sparsowany obiekt (np. Date lub LocalDate).
 */
public void setFormattedData(String data) {
    jFormattedData.setText(data);
}
public void setFieldLabels(String labelNazwisko, String labelNumer, String labelTelefon, 
                               String labelEmail, String labelData, String labelKategoria) {
        jLabel2.setText(labelNazwisko);
        jLabel7.setText(labelNumer);
        jLabel3.setText(labelTelefon);
        jLabel4.setText(labelEmail);
        jLabel5.setText(labelData);
        jLabel8.setText(labelKategoria);
        // jLabel6 jest dla Nicku, który jest oddzielony, więc go tu nie ma.
    }
public void setFieldVisible(Object field, boolean visible) {
        if (field instanceof JLabel label) {
            label.setVisible(visible);
        } else if (field instanceof JTextField textField) {
            textField.setVisible(visible);
        }
    }

// --- Metody do podpinania ActionListenerów (dodaj te metody) ---
public void addAkceptujListener(java.awt.event.ActionListener al) {
    jAkceptuj.addActionListener(al);
}

public void addAnulujListener(java.awt.event.ActionListener al) {
    jAnuluj.addActionListener(al);
}

}
