/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author kacpe
 */
public class DataUpdateWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataUpdateWindow.class.getName());

    /**
     * Creates new form DataUpdateWindow
     */
    public DataUpdateWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jKod = new javax.swing.JTextField();
        jNazwisko = new javax.swing.JTextField();
        jNumer = new javax.swing.JTextField();
        jTelefon = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jAkceptuj = new javax.swing.JButton();
        jAnuluj = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jKategoria = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jBirthdayChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTime = new javax.swing.JComboBox<>();
        jComboBoxTrener = new javax.swing.JComboBox<>();
        jComboBoxDay = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jKod.setEditable(false);
        jKod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKodActionPerformed(evt);
            }
        });

        jNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNazwiskoActionPerformed(evt);
            }
        });

        jNumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumerActionPerformed(evt);
            }
        });

        jTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonActionPerformed(evt);
            }
        });

        jEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Kod");

        jLabel2.setText("Imię i Nazwisko");

        jLabel3.setText("Telefon");

        jLabel4.setText("E-mail");

        jLabel5.setText("Data Przyjęcia/Wejścia");

        jLabel7.setText("Numer Identyfikacyjny");

        jAkceptuj.setBackground(new java.awt.Color(51, 255, 0));
        jAkceptuj.setForeground(new java.awt.Color(0, 0, 0));
        jAkceptuj.setText("Akceptuj");

        jAnuluj.setBackground(new java.awt.Color(255, 0, 0));
        jAnuluj.setForeground(new java.awt.Color(0, 0, 0));
        jAnuluj.setText("Anuluj");

        jLabel8.setText("Kategoria");

        jKategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKategoriaActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Urodzenia");

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxTrener.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTrener.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jComboBoxTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrenerActionPerformed(evt);
            }
        });

        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDay.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jAkceptuj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jAnuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jNumer, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jKod, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxTrener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jKategoria)
                                            .addComponent(jEmail)))
                                    .addComponent(jNazwisko, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBirthdayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBirthdayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnuluj)
                    .addComponent(jAkceptuj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKategoriaActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefonActionPerformed

    private void jNumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumerActionPerformed

    private void jNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNazwiskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNazwiskoActionPerformed

    private void jKodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKodActionPerformed

    private void jComboBoxTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataUpdateWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jAkceptuj;
    public javax.swing.JButton jAnuluj;
    public com.toedter.calendar.JDateChooser jBirthdayChooser;
    public javax.swing.JComboBox<String> jComboBoxDay;
    public javax.swing.JComboBox<String> jComboBoxTime;
    public javax.swing.JComboBox<String> jComboBoxTrener;
    public com.toedter.calendar.JDateChooser jDateChooser;
    public javax.swing.JTextField jEmail;
    public javax.swing.JTextField jKategoria;
    public javax.swing.JTextField jKod;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField jNazwisko;
    public javax.swing.JTextField jNumer;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTelefon;
    // End of variables declaration//GEN-END:variables

// Wewnątrz klasy Views.DataUpdateWindow:
// --- Metody pobierające dane z pól (dodaj te metody) ---
    public String getKod() {
        return jKod.getText();
    }

    public String getNazwisko() {
        return jNazwisko.getText();
    }

    public String getNumerIdentyfikacyjny() {
        return jNumer.getText(); // Zakładam, że to Numer Identyfikacyjny (ID)
    }

    public String getTelefon() {
        return jTelefon.getText();
    }

    public String getEmail() {
        return jEmail.getText();
    }

    public String getKategoria() {
        return jKategoria.getText();
    }

// Póki co Nick i Data zostawmy jako String, dla uproszczenia
// Data jest w JFormattedTextField
    

    public void setKod(String kod) {
        jKod.setText(kod);
    }

    public void setNazwisko(String nazwisko) {
        jNazwisko.setText(nazwisko);
    }

    public void setNumerIdentyfikacyjny(String numer) {
        jNumer.setText(numer);
    }

    public void setTelefon(String telefon) {
        jTelefon.setText(telefon);
    }

    public void setEmail(String email) {
        jEmail.setText(email);
    }

    public void setKategoria(String kategoria) {
        // UŻYWA jKategoria1, a NIE jFormattedData
        jKategoria.setText(kategoria);
    }

    public java.util.Date getSelectedDate() {
        return jDateChooser.getDate();
    }

// Ustawianie daty w kalendarzu
    public void setSelectedDate(java.util.Date date) {
        jDateChooser.setDate(date);
    }
public java.util.Date getBirthdayDate() {
    return jBirthdayChooser.getDate();
}

public void setBirthdayDate(java.util.Date date) {
    jBirthdayChooser.setDate(date);
}

// Opcjonalnie pomocniczy getter dla Stringa (jeśli potrzebujesz)
public String getBirthdayAsString() {
    if (jBirthdayChooser.getDate() != null) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(jBirthdayChooser.getDate());
    }
    return "";
}
// Jeśli jednak wolisz operować na Stringu (tak jak wcześniej w ActivityDataController),
// dodaj tę metodę, aby nie zmieniać zbyt dużo logiki w kontrolerze:
    public String getDateAsString() {
        if (jDateChooser.getDate() != null) {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            return sdf.format(jDateChooser.getDate());
        }
        return "";
    }

    /**
     * Ustawia wartość JFormattedTextField. Należy ustawiać sparsowany obiekt
     * (np. Date lub LocalDate).
     */
    

    public void setFieldLabels(String labelNazwisko, String labelNumer, String labelTelefon,
            String labelEmail, String labelData, String labelKategoria, String labelBirthday) {
        jLabel2.setText(labelNazwisko);
        jLabel7.setText(labelNumer);
        jLabel3.setText(labelTelefon);
        jLabel4.setText(labelEmail);
        jLabel5.setText(labelData);
        jLabel8.setText(labelKategoria);
        jLabel6.setText(labelBirthday); // jLabel6 to Data Urodzenia
        // jLabel6 jest dla Nicku, który jest oddzielony, więc go tu nie ma.
    }

    public void setFieldVisible(Object field, boolean visible) {
        if (field instanceof JLabel label) {
            label.setVisible(visible);
        } else if (field instanceof JTextField textField) {
            textField.setVisible(visible);
        }
    }

// --- Metody do podpinania ActionListenerów (dodaj te metody) ---
    public void addAkceptujListener(java.awt.event.ActionListener al) {
        jAkceptuj.addActionListener(al);
    }

    public void addAnulujListener(java.awt.event.ActionListener al) {
        jAnuluj.addActionListener(al);
    }

}
