/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author kacpe
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initializeMenuItems();
        initSearchListeners(); // <--- DODAJ TO
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jNowy = new javax.swing.JButton();
        jUsun = new javax.swing.JButton();
        jAktualizuj = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jSearchText = new javax.swing.JTextField();
        jSearchBox = new javax.swing.JComboBox<>();
        jSearchIcon = new javax.swing.JLabel();
        jPanelCalculate = new javax.swing.JPanel();
        jButtonCalculate = new javax.swing.JButton();
        jCalculateLabel = new javax.swing.JLabel();
        jPanelClientToActivity = new javax.swing.JPanel();
        jButtonClientToActivity = new javax.swing.JButton();
        jTextFieldClientToActivity = new javax.swing.JTextField();
        jComboBoxClientToActivity = new javax.swing.JComboBox<>();
        jLabelClientToA = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Main = new javax.swing.JMenu();
        Clients = new javax.swing.JMenu();
        Trainers = new javax.swing.JMenu();
        Activities = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(900, 450));

        viewNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewNameLabel.setText("Panel Główny");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(viewNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataTable.setBorder(new javax.swing.border.MatteBorder(null));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dataTable.setRowHeight(25);
        jScrollPane1.setViewportView(dataTable);

        jNowy.setBackground(new java.awt.Color(102, 255, 0));
        jNowy.setForeground(new java.awt.Color(0, 0, 0));
        jNowy.setText("Nowy ");
        jNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNowyActionPerformed(evt);
            }
        });

        jUsun.setBackground(new java.awt.Color(255, 0, 51));
        jUsun.setForeground(new java.awt.Color(0, 0, 0));
        jUsun.setText("Usuń");

        jAktualizuj.setBackground(new java.awt.Color(102, 204, 255));
        jAktualizuj.setForeground(new java.awt.Color(0, 0, 0));
        jAktualizuj.setText("Aktualizuj");

        jPanelSearch.setBackground(new java.awt.Color(255, 51, 255));

        jSearchText.setBorder(null);

        jSearchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBoxActionPerformed(evt);
            }
        });

        jSearchIcon.setBackground(new java.awt.Color(204, 0, 51));
        jSearchIcon.setForeground(new java.awt.Color(255, 102, 255));
        jSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jSearchIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSearchIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSearchLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSearchBox, jSearchIcon, jSearchText});

        jPanelCalculate.setBackground(new java.awt.Color(255, 204, 204));

        jButtonCalculate.setText("Oblicz");

        jCalculateLabel.setForeground(new java.awt.Color(0, 0, 0));
        jCalculateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCalculateLabel.setText("Oblicz statystyki dla aktywności");
        jCalculateLabel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanelCalculateLayout = new javax.swing.GroupLayout(jPanelCalculate);
        jPanelCalculate.setLayout(jPanelCalculateLayout);
        jPanelCalculateLayout.setHorizontalGroup(
            jPanelCalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalculateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalculate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCalculateLayout.setVerticalGroup(
            jPanelCalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCalculateLabel)
                    .addComponent(jButtonCalculate))
                .addContainerGap())
        );

        jPanelCalculateLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCalculate, jCalculateLabel});

        jPanelClientToActivity.setBackground(new java.awt.Color(255, 255, 51));

        jButtonClientToActivity.setText("Połącz");
        jButtonClientToActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientToActivityActionPerformed(evt);
            }
        });

        jComboBoxClientToActivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelClientToA.setForeground(new java.awt.Color(0, 0, 0));
        jLabelClientToA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientToA.setText("Połącz użytkownika z aktywnością");
        jLabelClientToA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelClientToActivityLayout = new javax.swing.GroupLayout(jPanelClientToActivity);
        jPanelClientToActivity.setLayout(jPanelClientToActivityLayout);
        jPanelClientToActivityLayout.setHorizontalGroup(
            jPanelClientToActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientToActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientToA, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelClientToActivityLayout.setVerticalGroup(
            jPanelClientToActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientToActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientToActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClientToActivity)
                    .addComponent(jComboBoxClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClientToA))
                .addContainerGap())
        );

        jPanelClientToActivityLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonClientToActivity, jComboBoxClientToActivity, jTextFieldClientToActivity});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelClientToActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAktualizuj, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanelCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jNowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUsun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAktualizuj)))
                .addGap(18, 18, 18)
                .addComponent(jPanelClientToActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Main.setText("Main");
        jMenuBar1.add(Main);

        Clients.setText("Clients");
        jMenuBar1.add(Clients);

        Trainers.setText("Trainers");
        jMenuBar1.add(Trainers);

        Activities.setText("Activities");
        jMenuBar1.add(Activities);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNowyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNowyActionPerformed

    private void jSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchBoxActionPerformed

    private void jButtonClientToActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientToActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientToActivityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    public void addClientMenuListener(java.awt.event.ActionListener al) {
        // Ustawienie ActionCommand jest kluczowe dla MainController
        clientManagerMenuItem.setActionCommand("ShowClients");
        clientManagerMenuItem.addActionListener(al);
    }

    public void addTrainerMenuListener(java.awt.event.ActionListener al) {
        trainerManagerMenuItem.setActionCommand("ShowTrainers");
        trainerManagerMenuItem.addActionListener(al);
    }

    public void addActivitiesMenuListener(java.awt.event.ActionListener al) {
        activitiesManagerMenuItem.setActionCommand("ShowActivities");
        activitiesManagerMenuItem.addActionListener(al);
    }

    public void addInitMenuListener(java.awt.event.ActionListener al) {
        initMenuItem.setActionCommand("ShowInit");
        initMenuItem.addActionListener(al);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Activities;
    public javax.swing.JMenu Clients;
    public javax.swing.JMenu Main;
    public javax.swing.JMenu Trainers;
    public javax.swing.JTable dataTable;
    public javax.swing.JButton jAktualizuj;
    public javax.swing.JButton jButtonCalculate;
    public javax.swing.JButton jButtonClientToActivity;
    public javax.swing.JLabel jCalculateLabel;
    public javax.swing.JComboBox<String> jComboBoxClientToActivity;
    public javax.swing.JLabel jLabelClientToA;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JButton jNowy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanelCalculate;
    public javax.swing.JPanel jPanelClientToActivity;
    public javax.swing.JPanel jPanelSearch;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jSearchBox;
    public javax.swing.JLabel jSearchIcon;
    public javax.swing.JTextField jSearchText;
    public javax.swing.JTextField jTextFieldClientToActivity;
    public javax.swing.JButton jUsun;
    public javax.swing.JLabel viewNameLabel;
    // End of variables declaration//GEN-END:variables
// ...
    private javax.swing.JMenuItem clientManagerMenuItem; // dla Clients
    private javax.swing.JMenuItem trainerManagerMenuItem; // dla Trainers
    private javax.swing.JMenuItem activitiesManagerMenuItem; // dla Activities
    private javax.swing.JMenuItem initMenuItem; // dla Main (Init)
    // ...
// =================================================================
    // API WIDOKU - Metody do komunikacji z Kontrolerem
    // =================================================================

    /**
     * Ustawia tytuł widoczny na środku ekranu (np. "Klienci", "Trenerzy").
     */
    public void setViewName(String name) {
        viewNameLabel.setText(name);
    }

    /**
     * Uzupełnia tabelę danymi i nazwami kolumn. Dodatkowo blokuje możliwość
     * ręcznej edycji komórek przez użytkownika.
     */
  public void setTableData(String[] columnNames, Object[][] data) {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

        @Override
        public Class<?> getColumnClass(int column) {
            // Sprawdzamy, co jest w pierwszej komórce danej kolumny
            if (getRowCount() > 0 && getValueAt(0, column) != null) {
                return getValueAt(0, column).getClass();
            }
            return Object.class;
        }
    };
    
  dataTable.setModel(model);

    if (data.length > 0 && data[0][0] instanceof javax.swing.Icon) {
        javax.swing.Icon icon = (javax.swing.Icon) data[0][0];
        
        // Ustawienie wysokości wiersza na dokładnie taką jak zdjęcie
        dataTable.setRowHeight(icon.getIconHeight());
        
        // Ustawienie szerokości kolumny na dokładnie taką jak zdjęcie
        dataTable.getColumnModel().getColumn(0).setPreferredWidth(icon.getIconWidth());
        
        // Wyłączenie nagłówka (opcjonalnie), aby zdjęcie wyglądało lepiej
        dataTable.getTableHeader().setVisible(false);
        jScrollPane1.setColumnHeaderView(null);
    } else {
        dataTable.setRowHeight(25);
        dataTable.getTableHeader().setVisible(true);
        // Przywrócenie nagłówka dla normalnych danych
        jScrollPane1.setColumnHeaderView(dataTable.getTableHeader());
        autoResizeColumns();
    }
}
    

    /**
     * Zwraca numer zaznaczonego wiersza w tabeli.
     *
     * @return numer wiersza lub -1, jeśli nic nie zaznaczono.
     */
   public int getSelectedRow() {
    // Zakładamy, że Twoja główna tabela to jTableData
    if (dataTable != null) {
        return dataTable.getSelectedRow();
    }
    return -1;
}

    /**
     * Pomocnicza metoda do pobierania wartości z zaznaczonego wiersza.
     * Przydatne do pobrania np. ID klienta (zakładając, że jest w kolumnie 0).
     */
    public Object getSelectedValueAt(int columnIndex) {
    int viewRow = dataTable.getSelectedRow();
    if (viewRow != -1) {
        // Konwertuje indeks widoku na indeks modelu (ważne przy filtrowaniu!)
        int modelRow = dataTable.convertRowIndexToModel(viewRow);
        return dataTable.getModel().getValueAt(modelRow, columnIndex);
    }
    return null;
}

    // --- LISTENERY PRZYCISKÓW (Podpinanie akcji) ---
    // Podpięcie akcji pod pierwszy przycisk (np. Dodaj)
    public void addNowyListener(java.awt.event.ActionListener al) {
        jNowy.addActionListener(al);
    }

    // Podpięcie akcji pod drugi przycisk (np. Edytuj)
    public void addUsunListener(java.awt.event.ActionListener al) {
        jUsun.addActionListener(al);
    }

    // Podpięcie akcji pod trzeci przycisk (np. Usuń)
    public void addAktualizujListener(java.awt.event.ActionListener al) {
        jAktualizuj.addActionListener(al);
    }

    // --- KONFIGURACJA PRZYCISKÓW ---
    /**
     * Pozwala dynamicznie zmieniać nazwy przycisków. Np. w widoku Klientów:
     * "Dodaj Klienta", a w widoku Trenerów: "Dodaj Trenera".
     */
    public void setButtonLabels(String btn1Text, String btn2Text, String btn3Text) {
        jNowy.setText(btn1Text);
        jUsun.setText(btn2Text);
        jAktualizuj.setText(btn3Text);
    }

    private void initializeMenuItems() {
        // Ręczna inicjalizacja JMenuItems, jeśli nie zostały utworzone w initComponents.
        // DZIĘKI TEMU PRZESTANĄ BYĆ NULL.

        if (clientManagerMenuItem == null) {
            clientManagerMenuItem = new javax.swing.JMenuItem("Client Manager");
            Clients.add(clientManagerMenuItem); // Dodaj element do menu Clients
        }

        if (trainerManagerMenuItem == null) {
            trainerManagerMenuItem = new javax.swing.JMenuItem("Trainer Manager");
            Trainers.add(trainerManagerMenuItem);
        }

        if (activitiesManagerMenuItem == null) {
            activitiesManagerMenuItem = new javax.swing.JMenuItem("Activities Manager");
            Activities.add(activitiesManagerMenuItem);
        }

        if (initMenuItem == null) {
            initMenuItem = new javax.swing.JMenuItem("Initialize");
            Main.add(initMenuItem);
        }
    }
public String getSelectedClientCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }

    /**
     * Zwraca kod Trenera (ID) z zaznaczonego wiersza.
     * Zakłada, że Kod Trenera jest w kolumnie 0.
     */
    public String getSelectedTrainerCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }

    /**
     * Zwraca kod Aktywności (ID) z zaznaczonego wiersza.
     * Zakłada, że Kod Aktywności jest w kolumnie 0.
     */
    public String getSelectedActivityCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }
    
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;

/**
 * Konfiguruje sorter tabeli i wypełnia JComboBox nazwami kolumn.
 */
public void setupTableSorter() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) dataTable.getModel();
    sorter = new javax.swing.table.TableRowSorter<>(model);
    dataTable.setRowSorter(sorter);

    // Automatyczne wypełnienie ComboBoxa aktualnymi nazwami kolumn
    jSearchBox.removeAllItems();
    for (int i = 0; i < model.getColumnCount(); i++) {
        jSearchBox.addItem(model.getColumnName(i));
    }
}

/**
 * Logika filtrowania wierszy.
 */
private void filterTable() {
    if (sorter == null) return;

    String text = jSearchText.getText();
    int columnIndex = jSearchBox.getSelectedIndex();

    if (text.trim().isEmpty()) {
        sorter.setRowFilter(null);
    } else {
        // (?i) oznacza ignorowanie wielkości liter
        try {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text, columnIndex));
        } catch (java.util.regex.PatternSyntaxException e) {
            // W razie błędu w składni regex nie rób nic
        }
    }
}

/**
 * Dodaje listenery do pól wyszukiwania. Wywołaj to w konstruktorze MainWindow.
 */
public void initSearchListeners() {
    // Reaguj na pisanie w polu tekstowym
    jSearchText.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void changedUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
    });

    // Reaguj na zmianę kolumny w ComboBox
    jSearchBox.addActionListener(e -> filterTable());
}


public void setClientToActivityName(String name) {
    jTextFieldClientToActivity.setText(name);
}

// Pobiera wybraną aktywność z ComboBoxa (zwraca obiekt Activity lub String)
public Object getSelectedActivityFromCombo() {
    return jComboBoxClientToActivity.getSelectedItem();
}

// Dodaje listener do przycisku "Dodaj Aktywność"
public void addClientToActivityListener(java.awt.event.ActionListener al) {
    jButtonClientToActivity.addActionListener(al);
}

// Dodaje listener do tabeli, aby reagować na kliknięcia wierszy
public void addTableSelectionListener(javax.swing.event.ListSelectionListener lsl) {
    dataTable.getSelectionModel().addListSelectionListener(lsl);
}

  public void autoResizeColumns() {
    dataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    
    for (int column = 0; column < dataTable.getColumnCount(); column++) {
        javax.swing.table.TableColumn tableColumn = dataTable.getColumnModel().getColumn(column);
        
        // 1. Sprawdź szerokość NAGŁÓWKA (Tytułu kolumny)
        javax.swing.table.TableCellRenderer headerRenderer = dataTable.getTableHeader().getDefaultRenderer();
        java.awt.Component headerComp = headerRenderer.getTableCellRendererComponent(
                dataTable, tableColumn.getHeaderValue(), false, false, 0, column);
        int width = headerComp.getPreferredSize().width + 20; // +20 dla marginesu i strzałki sortowania

        // 2. Sprawdź szerokość KOMÓREK w tej kolumnie
        for (int row = 0; row < dataTable.getRowCount(); row++) {
            javax.swing.table.TableCellRenderer cellRenderer = dataTable.getCellRenderer(row, column);
            java.awt.Component c = dataTable.prepareRenderer(cellRenderer, row, column);
            int cellWidth = c.getPreferredSize().width + dataTable.getIntercellSpacing().width + 10;
            width = Math.max(width, cellWidth);
        }

        // 3. Ustaw ostateczną szerokość
        tableColumn.setPreferredWidth(width);
    }
}
}
