/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author kacpe
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initializeMenuItems();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jNowy = new javax.swing.JButton();
        jUsun = new javax.swing.JButton();
        jAktualizuj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Main = new javax.swing.JMenu();
        Clients = new javax.swing.JMenu();
        Trainers = new javax.swing.JMenu();
        Activities = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewNameLabel.setText("Panel Główny");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewNameLabel)
                .addGap(356, 356, 356))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(viewNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataTable.setBorder(new javax.swing.border.MatteBorder(null));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        jNowy.setBackground(new java.awt.Color(102, 255, 0));
        jNowy.setForeground(new java.awt.Color(0, 0, 0));
        jNowy.setText("Nowy ");
        jNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNowyActionPerformed(evt);
            }
        });

        jUsun.setBackground(new java.awt.Color(255, 0, 51));
        jUsun.setForeground(new java.awt.Color(0, 0, 0));
        jUsun.setText("Usuń");

        jAktualizuj.setBackground(new java.awt.Color(102, 204, 255));
        jAktualizuj.setForeground(new java.awt.Color(0, 0, 0));
        jAktualizuj.setText("Aktualizuj");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAktualizuj, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jNowy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAktualizuj)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        Main.setText("Main");
        jMenuBar1.add(Main);

        Clients.setText("Clients");
        jMenuBar1.add(Clients);

        Trainers.setText("Trainers");
        jMenuBar1.add(Trainers);

        Activities.setText("Activities");
        jMenuBar1.add(Activities);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNowyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNowyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    public void addClientMenuListener(java.awt.event.ActionListener al) {
        // Ustawienie ActionCommand jest kluczowe dla MainController
        clientManagerMenuItem.setActionCommand("ShowClients");
        clientManagerMenuItem.addActionListener(al);
    }

    public void addTrainerMenuListener(java.awt.event.ActionListener al) {
        trainerManagerMenuItem.setActionCommand("ShowTrainers");
        trainerManagerMenuItem.addActionListener(al);
    }

    public void addActivitiesMenuListener(java.awt.event.ActionListener al) {
        activitiesManagerMenuItem.setActionCommand("ShowActivities");
        activitiesManagerMenuItem.addActionListener(al);
    }

    public void addInitMenuListener(java.awt.event.ActionListener al) {
        initMenuItem.setActionCommand("ShowInit");
        initMenuItem.addActionListener(al);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Activities;
    public javax.swing.JMenu Clients;
    public javax.swing.JMenu Main;
    public javax.swing.JMenu Trainers;
    public javax.swing.JTable dataTable;
    public javax.swing.JButton jAktualizuj;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JButton jNowy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jUsun;
    public javax.swing.JLabel viewNameLabel;
    // End of variables declaration//GEN-END:variables
// ...
    private javax.swing.JMenuItem clientManagerMenuItem; // dla Clients
    private javax.swing.JMenuItem trainerManagerMenuItem; // dla Trainers
    private javax.swing.JMenuItem activitiesManagerMenuItem; // dla Activities
    private javax.swing.JMenuItem initMenuItem; // dla Main (Init)
    // ...
// =================================================================
    // API WIDOKU - Metody do komunikacji z Kontrolerem
    // =================================================================

    /**
     * Ustawia tytuł widoczny na środku ekranu (np. "Klienci", "Trenerzy").
     */
    public void setViewName(String name) {
        viewNameLabel.setText(name);
    }

    /**
     * Uzupełnia tabelę danymi i nazwami kolumn. Dodatkowo blokuje możliwość
     * ręcznej edycji komórek przez użytkownika.
     */
    public void setTableData(String[] columnNames, Object[][] data) {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Zwraca false, żeby użytkownik nie mógł wpisywać w tabelę ręcznie
                return false;
            }
        };
        dataTable.setModel(model);
    }
    

    /**
     * Zwraca numer zaznaczonego wiersza w tabeli.
     *
     * @return numer wiersza lub -1, jeśli nic nie zaznaczono.
     */
   public int getSelectedRow() {
    // Zakładamy, że Twoja główna tabela to jTableData
    if (dataTable != null) {
        return dataTable.getSelectedRow();
    }
    return -1;
}

    /**
     * Pomocnicza metoda do pobierania wartości z zaznaczonego wiersza.
     * Przydatne do pobrania np. ID klienta (zakładając, że jest w kolumnie 0).
     */
    public Object getSelectedValueAt(int columnIndex) {
        int row = dataTable.getSelectedRow();
        if (row != -1) {
            return dataTable.getValueAt(row, columnIndex);
        }
        return null;
    }

    // --- LISTENERY PRZYCISKÓW (Podpinanie akcji) ---
    // Podpięcie akcji pod pierwszy przycisk (np. Dodaj)
    public void addNowyListener(java.awt.event.ActionListener al) {
        jNowy.addActionListener(al);
    }

    // Podpięcie akcji pod drugi przycisk (np. Edytuj)
    public void addUsunListener(java.awt.event.ActionListener al) {
        jUsun.addActionListener(al);
    }

    // Podpięcie akcji pod trzeci przycisk (np. Usuń)
    public void addAktualizujListener(java.awt.event.ActionListener al) {
        jAktualizuj.addActionListener(al);
    }

    // --- KONFIGURACJA PRZYCISKÓW ---
    /**
     * Pozwala dynamicznie zmieniać nazwy przycisków. Np. w widoku Klientów:
     * "Dodaj Klienta", a w widoku Trenerów: "Dodaj Trenera".
     */
    public void setButtonLabels(String btn1Text, String btn2Text, String btn3Text) {
        jNowy.setText(btn1Text);
        jUsun.setText(btn2Text);
        jAktualizuj.setText(btn3Text);
    }

    private void initializeMenuItems() {
        // Ręczna inicjalizacja JMenuItems, jeśli nie zostały utworzone w initComponents.
        // DZIĘKI TEMU PRZESTANĄ BYĆ NULL.

        if (clientManagerMenuItem == null) {
            clientManagerMenuItem = new javax.swing.JMenuItem("Client Manager");
            Clients.add(clientManagerMenuItem); // Dodaj element do menu Clients
        }

        if (trainerManagerMenuItem == null) {
            trainerManagerMenuItem = new javax.swing.JMenuItem("Trainer Manager");
            Trainers.add(trainerManagerMenuItem);
        }

        if (activitiesManagerMenuItem == null) {
            activitiesManagerMenuItem = new javax.swing.JMenuItem("Activities Manager");
            Activities.add(activitiesManagerMenuItem);
        }

        if (initMenuItem == null) {
            initMenuItem = new javax.swing.JMenuItem("Initialize");
            Main.add(initMenuItem);
        }
    }
public String getSelectedClientCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }

    /**
     * Zwraca kod Trenera (ID) z zaznaczonego wiersza.
     * Zakłada, że Kod Trenera jest w kolumnie 0.
     */
    public String getSelectedTrainerCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }

    /**
     * Zwraca kod Aktywności (ID) z zaznaczonego wiersza.
     * Zakłada, że Kod Aktywności jest w kolumnie 0.
     */
    public String getSelectedActivityCode() {
        Object value = getSelectedValueAt(0); // Zakładamy, że ID jest w kolumnie 0
        return (value != null) ? value.toString() : null;
    }
    
}
